services:
  Postgress:
    container_name: Postgres_container
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=secretpostgres1
      - PGDATA=/data/postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-secretpgadmin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    restart: unless-stopped

  jobapp:
    container_name: Springboot_jobapp_container
    image: itslohith/jobappimage
    ports:
      - "8080:8080"
    networks:
      - postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://Postgres_container:5432/jobapp
      - spring.datasource.username=postgres1
      - spring.datasource.password=secretpostgres1
    depends_on:
      - Postgress
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
